apiVersion: apps/v1
kind: Deployment
metadata:
  name: ey-cart-deploy
  namespace: thanu-ns
  labels:
    app: cart
spec: 
  replicas: 5
  selector: 
    matchLabels:
      app: ey
  template:
    metadata:
      labels:
        app: ey
    spec: 
      containers:
        - name: ey-cart-container
          image: thanusri22/flower:v1.1.0

          ports:
            - containerPort: 3015
