apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-deployment
  namespace: thanu-ns
  labels:
    app: fitness
spec: 
  replicas: 8
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector: 
    matchLabels:
      app: fit
  template:
    metadata:
      labels:
        app: fit
    spec: 
      containers:
        - name: fitness-container
          image: muralisocial123/fitness-app:v1.0.1
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: fitness-deployment-svc 
  namespace: thanu-ns
spec:
  selector:
    app: fitness
  ports:
    - port: 3001 #it is a service port number we are using app to the internet 
      targetPort: 3000
      protocol: TCP
  type: ClusterIP     
    