apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name:ey-cart-rs 
  namespace: thanu-ns
  labels:
    app: cart
spec: #it defines the behaviour of the replicaset
  replicas: 3
  selector: #it defines how the replicaset finds which pod to manage
    matchLabels:
      app: web
  template: #It contains pod definition
    metadata:
      labels:
        app: web
spec: # It contains the container definition
  containers:
    - name: ey-cart-container
      image:  muralisocial123/ey-cart:v1.1.0
      ports:
        - containerPort: 3000
